/* Daily Stoic Quotes — paraphrased principles from classical Stoic philosophy */
const STOIC_QUOTES = [
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", theme: "control" },
  { text: "It is not things that disturb us, but our judgments about things.", author: "Epictetus", theme: "perception" },
  { text: "We suffer more in imagination than in reality.", author: "Seneca", theme: "anxiety" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", theme: "mindset" },
  { text: "No person is free who is not master of themselves.", author: "Epictetus", theme: "discipline" },
  { text: "Waste no more time arguing about what a good person should be. Be one.", author: "Marcus Aurelius", theme: "action" },
  { text: "He who angers you conquers you.", author: "Seneca", theme: "anger" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius", theme: "character" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca", theme: "resilience" },
  { text: "First say to yourself what you would be; then do what you have to do.", author: "Epictetus", theme: "purpose" },
  { text: "If it is not right, do not do it. If it is not true, do not say it.", author: "Marcus Aurelius", theme: "integrity" },
  { text: "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.", author: "Seneca", theme: "anger" },
  { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus", theme: "action" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius", theme: "mindset" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca", theme: "presence" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", theme: "control" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius", theme: "gratitude" },
  { text: "A gem cannot be polished without friction, nor a person perfected without trials.", author: "Seneca", theme: "resilience" },
  { text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", author: "Seneca", theme: "courage" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", theme: "obstacles" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", theme: "temperance" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius", theme: "urgency" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca", theme: "preparation" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus", theme: "anger" },
  { text: "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.", author: "Marcus Aurelius", theme: "wisdom" },
  { text: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", author: "Seneca", theme: "fear" },
  { text: "Other people's views and troubles can be contagious. Do not sabotage yourself by unwittingly adopting negative attitudes.", author: "Epictetus", theme: "boundaries" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius", theme: "acceptance" },
  { text: "It is the power of the mind to be unconquerable.", author: "Seneca", theme: "strength" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus", theme: "action" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", theme: "contentment" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", theme: "presence" },
  { text: "There is only one way to happiness, and that is to cease worrying about things which are beyond our power.", author: "Epictetus", theme: "control" },
  { text: "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.", author: "Marcus Aurelius", theme: "integrity" },
  { text: "While we wait for life, life passes.", author: "Seneca", theme: "urgency" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus", theme: "freedom" },
  { text: "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.", author: "Marcus Aurelius", theme: "perspective" },
  { text: "All cruelty springs from weakness.", author: "Seneca", theme: "strength" },
  { text: "If anyone tells you that a certain person speaks ill of you, do not make excuses — answer that they were ignorant of your other faults.", author: "Epictetus", theme: "humor" },
  { text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius", theme: "perception" },
  { text: "Hang on to your youthful enthusiasms — you will be able to use them better when you are older.", author: "Seneca", theme: "growth" },
  { text: "People are not disturbed by things, but by the views they take of them.", author: "Epictetus", theme: "perception" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", theme: "character" },
  { text: "The greatest obstacle to living is expectancy, which depends on tomorrow and wastes today.", author: "Seneca", theme: "presence" },
  { text: "Caretake this moment. Immerse yourself in its particulars.", author: "Epictetus", theme: "mindfulness" },
  { text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius", theme: "perception" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca", theme: "growth" },
  { text: "Circumstance does not make the person; it reveals them to themselves.", author: "Epictetus", theme: "character" },
  { text: "The best way to avenge yourself is to not be like the wrongdoer.", author: "Marcus Aurelius", theme: "character" },
  { text: "Sometimes even to live is an act of courage.", author: "Seneca", theme: "courage" },
  { text: "Attach yourself to what is spiritually superior, regardless of what other people think or do.", author: "Epictetus", theme: "values" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius", theme: "strength" },
  { text: "The mind that is anxious about future events is miserable.", author: "Seneca", theme: "anxiety" },
  { text: "Practice yourself in the things you can control, and accept the things you cannot.", author: "Epictetus", theme: "control" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", theme: "wonder" },
  { text: "Life is long if you know how to use it.", author: "Seneca", theme: "time" },
  { text: "No great thing is created suddenly, any more than a bunch of grapes or a fig.", author: "Epictetus", theme: "patience" },
  { text: "Loss is nothing else but change, and change is nature's delight.", author: "Marcus Aurelius", theme: "impermanence" },
  { text: "Associate with people who are likely to improve you.", author: "Seneca", theme: "company" },
  { text: "Seeking to understand before seeking to be understood is the mark of wisdom.", author: "Epictetus", theme: "wisdom" },
  { text: "How much more grievous are the consequences of anger than the causes of it.", author: "Marcus Aurelius", theme: "anger" },
  { text: "The mind is sharper and keener in seclusion and quiet.", author: "Seneca", theme: "solitude" },
  { text: "What concerns me is not the way things are, but the way people think things are.", author: "Epictetus", theme: "perception" },
  { text: "Receive without pride, let go without attachment.", author: "Marcus Aurelius", theme: "detachment" },
  { text: "He who is brave is free.", author: "Seneca", theme: "courage" },
  { text: "Deliberate much before saying or doing anything, for you will not have the power of recalling what has been said or done.", author: "Epictetus", theme: "restraint" },
  { text: "Think of yourself as dead. You have lived your life. Now take what is left and live it properly.", author: "Marcus Aurelius", theme: "urgency" },
  { text: "One of the most beautiful qualities of true friendship is to understand and be understood.", author: "Seneca", theme: "connection" },
  { text: "Keep your attention focused entirely on what is truly your own concern, and be clear that what belongs to others is their business.", author: "Epictetus", theme: "boundaries" },
  { text: "Our anger and annoyance are more detrimental to us than the things themselves which anger or annoy us.", author: "Marcus Aurelius", theme: "anger" },
  { text: "Enjoy present pleasures in such a way as not to injure future ones.", author: "Seneca", theme: "temperance" },
  { text: "To accuse others for one's own misfortunes is a sign of lack of education. To accuse oneself shows that one's education has begun.", author: "Epictetus", theme: "responsibility" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius", theme: "presence" },
  { text: "If a person gave your body to a passerby, you would be furious. Yet you hand your mind to anyone who insults you.", author: "Epictetus", theme: "mental-guard" },
  { text: "Choose not to be harmed, and you won't feel harmed. Don't feel harmed, and you haven't been.", author: "Marcus Aurelius", theme: "perception" },
  { text: "There is no genius without a touch of madness.", author: "Seneca", theme: "creativity" },
  { text: "It is impossible for a person to begin to learn what they think they already know.", author: "Epictetus", theme: "humility" },
  { text: "Adapt yourself to the things among which your lot has been cast, and love sincerely the fellow creatures with whom destiny has ordained that you shall live.", author: "Marcus Aurelius", theme: "community" },
  { text: "Throw me to the wolves and I will return leading the pack.", author: "Seneca", theme: "resilience" },
  { text: "Only the educated are free.", author: "Epictetus", theme: "education" },
  { text: "Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess.", author: "Marcus Aurelius", theme: "gratitude" },
  { text: "Every new beginning comes from some other beginning's end.", author: "Seneca", theme: "change" },
  { text: "Know first who you are, and then adorn yourself accordingly.", author: "Epictetus", theme: "identity" },
  { text: "Nothing happens to anybody which they are not fitted by nature to bear.", author: "Marcus Aurelius", theme: "endurance" },
  { text: "Hang on to your youthful enthusiasms — you will be able to use them better when you are older.", author: "Seneca", theme: "vitality" },
  { text: "The key is to keep company only with people who uplift you.", author: "Epictetus", theme: "company" },
  { text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius", theme: "mindset" },
  { text: "If you wish to be loved, love.", author: "Seneca", theme: "love" },
  { text: "Permit nothing to cleave to you that is not your own.", author: "Epictetus", theme: "detachment" },
  { text: "I shall meet today ungrateful, violent, treacherous, envious, uncharitable people. I shall not be surprised or disturbed, for I cannot imagine a world without such.", author: "Marcus Aurelius", theme: "preparation" },
  { text: "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.", author: "Seneca", theme: "anger" },
  { text: "What really frightens and dismays us is not external events themselves, but the way in which we think about them.", author: "Epictetus", theme: "perception" },
  { text: "When someone is properly grounded in life, they shouldn't have to look outside themselves for approval.", author: "Epictetus", theme: "self-reliance" },
  { text: "Consider how much more you often suffer from your anger and grief than from those very things for which you are angry and grieved.", author: "Marcus Aurelius", theme: "anger" },
  { text: "Brave is not the one who has no fear, but the one who acts despite it.", author: "Seneca", theme: "courage" },
  { text: "The things you think about determine the quality of your mind.", author: "Marcus Aurelius", theme: "mindset" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus", theme: "growth" },
  { text: "Every day, acquire something that will fortify you against poverty, against death, against other misfortunes.", author: "Seneca", theme: "preparation" },
  { text: "Today I escaped anxiety. Or no, I discarded it, because it was within me — in my own perceptions, not outside.", author: "Marcus Aurelius", theme: "agency" },
  { text: "Don't seek for everything to happen as you wish, but wish for everything to happen as it actually does, and your life will be serene.", author: "Epictetus", theme: "acceptance" },
  { text: "While we are postponing, life speeds by.", author: "Seneca", theme: "urgency" },
  { text: "You are a little soul carrying about a corpse.", author: "Epictetus", theme: "perspective" },
  { text: "At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being.", author: "Marcus Aurelius", theme: "duty" },
  { text: "Hold every hour in your grasp. Lay hold of today's task, and you will not need to depend so much upon tomorrow's.", author: "Seneca", theme: "presence" },
  { text: "Progress is not achieved by luck or accident, but by working on yourself daily.", author: "Epictetus", theme: "discipline" },
  { text: "Never value anything as profitable that compels you to break your promise, to lose your self-respect, to hate any person, to suspect, to curse.", author: "Marcus Aurelius", theme: "values" },
  { text: "The willing are led by fate, the reluctant dragged.", author: "Seneca", theme: "acceptance" },
  { text: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", author: "Epictetus", theme: "anxiety" },
  { text: "To live a good life: we have the potential for it. If we learn to be indifferent to what makes no difference.", author: "Marcus Aurelius", theme: "equanimity" },
  { text: "We learn not in school, but in life.", author: "Seneca", theme: "experience" },
  { text: "It is difficulties that show what people are.", author: "Epictetus", theme: "character" },
  { text: "Here is a rule to remember in future, when anything tempts you to feel bitter: not 'This is misfortune,' but 'To bear this worthily is good fortune.'", author: "Marcus Aurelius", theme: "reframing" },
  { text: "A sword never kills anybody; it is a tool in the killer's hand.", author: "Seneca", theme: "responsibility" },
  { text: "Remind yourself that past your skin is a skeleton, and between the skeleton and the skin are muscles, blood, and various tissues. So much for glamour.", author: "Epictetus", theme: "perspective" },
  { text: "The best answer to anger is silence.", author: "Marcus Aurelius", theme: "anger" },
];

function getTodayQuote() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now - start) / (1000 * 60 * 60 * 24));
  return STOIC_QUOTES[dayOfYear % STOIC_QUOTES.length];
}
